import { useState, useEffect, useCallback } from "react";
import { FileText, Download, RefreshCw, CheckCircle2, Clock, AlertCircle, BarChart3, Users, CalendarDays, FileSpreadsheet, Printer } from "lucide-react";
import { motion } from "motion/react";
import { api, exportToCsv } from "../../lib/api";
import { PasswordPrompt } from "../components/PasswordPrompt";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface GeneratedReport {
  id: string;
  name: string;
  type: string;
  generated_at: string;
  generated_by: string;
  status: "ready" | "generating" | "failed";
  size: string;
  rows?: any[];
}

const reportTemplates = [
  { id: "attendance-summary", label: "Attendance Summary", icon: Clock, desc: "Daily/monthly attendance overview", color: "text-purple-600 bg-purple-50", type: "Attendance", fetcher: () => api.getAttendanceSummaryReport() },
  { id: "headcount", label: "Headcount Report", icon: Users, desc: "Employee count by department", color: "text-blue-600 bg-blue-50", type: "Headcount", fetcher: () => api.getHeadcountReport() },
  { id: "leave-summary", label: "Leave Summary", icon: CalendarDays, desc: "Leave utilization and balances", color: "text-emerald-600 bg-emerald-50", type: "Leave", fetcher: () => api.getLeaveSummaryReport() },
  { id: "timesheet", label: "Timesheet Report", icon: FileSpreadsheet, desc: "Work hours and overtime", color: "text-amber-600 bg-amber-50", type: "Timesheet", fetcher: () => api.getTimesheetReport() },
  { id: "overtime", label: "Overtime Analysis", icon: BarChart3, desc: "Performance and trend data", color: "text-red-600 bg-red-50", type: "Overtime", fetcher: () => api.getOvertimeReport() },
  { id: "audit-export", label: "Audit Log Export", icon: FileText, desc: "System activity and changes", color: "text-gray-600 bg-gray-50", type: "Audit", fetcher: () => api.getAuditExportReport() },
];

const statusConfig = {
  ready:      { label: "Ready",      className: "bg-emerald-100 text-emerald-700", icon: CheckCircle2 },
  generating: { label: "Generating", className: "bg-blue-100 text-blue-700",       icon: RefreshCw },
  failed:     { label: "Failed",     className: "bg-red-100 text-red-700",         icon: AlertCircle },
};

const typeColors: Record<string, string> = {
  Attendance: "bg-purple-100 text-purple-700",
  Headcount:  "bg-blue-100 text-blue-700",
  Leave:      "bg-emerald-100 text-emerald-700",
  Overtime:   "bg-orange-100 text-orange-700",
  Timesheet:  "bg-amber-100 text-amber-700",
  Audit:      "bg-gray-100 text-gray-700",
};

function exportToPdf(reportName: string, rows: any[], reportType: string, generatedBy: string) {
  if (!rows || rows.length === 0) {
    alert("No data to export to PDF.");
    return;
  }

  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();

  doc.setFillColor(124, 58, 237);
  doc.rect(0, 0, pageWidth, 70, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.text("Tri-M Global Logistics & Trading Inc.", 40, 32);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Workforce Management System", 40, 50);

  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text(reportType.toUpperCase(), pageWidth - 40, 32, { align: "right" });
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.text(reportName, pageWidth - 40, 50, { align: "right" });

  doc.setTextColor(80, 80, 80);
  doc.setFontSize(9);
  doc.text(`Generated by: ${generatedBy}`, 40, 90);
  doc.text(`Generated at: ${new Date().toLocaleString("en-US")}`, 40, 104);
  doc.text(`Total records: ${rows.length}`, 40, 118);

  const headers = Object.keys(rows[0]);
  const body = rows.map((r) => headers.map((h) => {
    const v = r[h];
    if (v === null || v === undefined) return "—";
    if (typeof v === "object") return JSON.stringify(v);
    return String(v);
  }));

  autoTable(doc, {
    head: [headers.map((h) => h.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase()))],
    body,
    startY: 135,
    styles: { fontSize: 8, cellPadding: 5, overflow: "linebreak" },
    headStyles: { fillColor: [124, 58, 237], textColor: 255, fontStyle: "bold" },
    alternateRowStyles: { fillColor: [245, 243, 255] },
    margin: { left: 40, right: 40 },
    didDrawPage: () => {
      const pageHeight = doc.internal.pageSize.getHeight();
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Tri-M Global — Confidential | Page ${doc.getNumberOfPages()}`,
        pageWidth / 2,
        pageHeight - 20,
        { align: "center" }
      );
    },
  });

  const safeName = reportName.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  doc.save(`${safeName}.pdf`);
}

export function ReportsPage() {
  const [generating, setGenerating] = useState<string | null>(null);
  const [reports, setReports] = useState<GeneratedReport[]>([]);
  const [summary, setSummary] = useState({ totalReports: 6, ready: 0 });
  const [currentUserName, setCurrentUserName] = useState("System");

  // 🔒 Password prompt state
  const [showPasswordPrompt, setShowPasswordPrompt] = useState(false);
  const [pendingAction, setPendingAction] = useState<(() => void) | null>(null);
  const [promptTitle, setPromptTitle] = useState("Password Required");
  const [promptDescription, setPromptDescription] = useState("");

  const loadSummary = useCallback(async () => {
    try {
      const data = await api.getReportsSummary();
      setSummary(data);
    } catch (err) {
      console.error("Failed to load reports summary", err);
    }
  }, []);

  useEffect(() => {
    loadSummary();
    api.me().then((user) => setCurrentUserName(user?.full_name ?? "System")).catch(() => {});
  }, [loadSummary]);

  function requirePassword(title: string, description: string, action: () => void) {
    setPromptTitle(title);
    setPromptDescription(description);
    setPendingAction(() => action);
    setShowPasswordPrompt(true);
  }

  async function handleGenerate(tpl: typeof reportTemplates[number]) {
    setGenerating(tpl.id);
    try {
      const data = await tpl.fetcher();
      const rows = data.rows ?? [];
      const sizeKB = rows.length ? (JSON.stringify(rows).length / 1024).toFixed(1) : "0";

      const newReport: GeneratedReport = {
        id: `${tpl.id}-${Date.now()}`,
        name: `${tpl.label} — ${new Date().toLocaleDateString("en-US", { month: "long", year: "numeric" })}`,
        type: tpl.type,
        generated_at: new Date().toISOString().slice(0, 16).replace("T", " "),
        generated_by: currentUserName,
        status: "ready",
        size: rows.length ? `${sizeKB} KB` : "0 KB (no data)",
        rows,
      };
      setReports((prev) => [newReport, ...prev]);

      // 🔒 Hilingin ang password bago mag-download ng CSV
      if (rows.length) {
        requirePassword(
          "Download Report",
          `Enter your password to download "${tpl.label}" as CSV.`,
          () => exportToCsv(`${tpl.id}-${Date.now()}`, rows)
        );
      } else {
        console.info(`${tpl.label}: generated successfully but no rows found for this period.`);
      }
    } catch (err) {
      console.error(`Failed to generate ${tpl.id}`, err);
      setReports((prev) => [
        {
          id: `${tpl.id}-${Date.now()}`,
          name: `${tpl.label} (failed)`,
          type: tpl.type,
          generated_at: new Date().toISOString().slice(0, 16).replace("T", " "),
          generated_by: currentUserName,
          status: "failed",
          size: "—",
        },
        ...prev,
      ]);
    } finally {
      setGenerating(null);
      loadSummary();
    }
  }

  function handleDownloadPdf(report: GeneratedReport) {
    if (!report.rows || report.rows.length === 0) {
      alert("No data available for this report. Please generate a new one.");
      return;
    }
    requirePassword(
      "Download PDF",
      `Enter your password to download "${report.name}" as PDF.`,
      () => exportToPdf(report.name, report.rows!, report.type, report.generated_by)
    );
  }

  function handleDownloadCsv(report: GeneratedReport) {
    if (!report.rows || report.rows.length === 0) {
      alert("No data available for this report.");
      return;
    }
    requirePassword(
      "Download CSV",
      `Enter your password to download "${report.name}" as CSV.`,
      () => exportToCsv(report.name.replace(/[^a-z0-9]/gi, "_").toLowerCase(), report.rows!)
    );
  }

  return (
    <div className="p-4 sm:p-6 space-y-4 sm:space-y-6">
      <motion.div
        initial={{ opacity: 0, y: -10 }}
        animate={{ opacity: 1, y: 0 }}
        className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-primary via-violet-600 to-indigo-700 p-5 sm:p-6 text-white shadow-lg"
      >
        <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between">
          <div className="min-w-0">
            <h1 className="text-xl sm:text-2xl font-bold flex items-center gap-2">
              <FileText className="w-6 h-6 sm:w-7 sm:h-7" /> Reports
            </h1>
            <p className="text-white/70 text-xs sm:text-sm mt-1">Generate and download workforce reports</p>
          </div>
          <div className="grid grid-cols-2 gap-2 sm:gap-3 shrink-0">
            {[
              { label: "Total Reports", value: summary.totalReports },
              { label: "Ready", value: summary.ready },
            ].map((s) => (
              <div key={s.label} className="bg-white/10 rounded-xl px-3 py-2 sm:px-4 border border-white/20 text-center">
                <p className="text-white/60 text-[10px] sm:text-xs">{s.label}</p>
                <p className="text-white font-bold text-lg sm:text-xl">{s.value}</p>
              </div>
            ))}
          </div>
        </div>
      </motion.div>

      <div>
        <h2 className="font-semibold text-foreground mb-3">Generate New Report</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
          {reportTemplates.map((tpl, i) => (
            <motion.button
              key={tpl.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.04 }}
              onClick={() => handleGenerate(tpl)}
              disabled={generating === tpl.id}
              aria-label={`Generate ${tpl.label} report`}
              className="flex items-center gap-3 p-4 bg-card rounded-xl border border-border hover:border-primary/30 hover:shadow-md transition-all text-left disabled:opacity-60 focus:outline-none focus:ring-2 focus:ring-primary/40"
            >
              <div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 ${tpl.color}`}>
                {generating === tpl.id
                  ? <RefreshCw className="w-5 h-5 animate-spin" />
                  : <tpl.icon className="w-5 h-5" />
                }
              </div>
              <div className="min-w-0">
                <p className="font-medium text-sm text-foreground truncate">{tpl.label}</p>
                <p className="text-xs text-muted-foreground truncate">{tpl.desc}</p>
              </div>
            </motion.button>
          ))}
        </div>
      </div>

      <div>
        <h2 className="font-semibold text-foreground mb-3">Recent Reports</h2>
        <div className="bg-card rounded-2xl shadow-sm border border-border overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full min-w-[800px]">
              <thead>
                <tr className="border-b border-border bg-muted/30">
                  <th className="text-left px-4 sm:px-5 py-3.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide whitespace-nowrap">Report Name</th>
                  <th className="text-left px-4 sm:px-5 py-3.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide whitespace-nowrap">Type</th>
                  <th className="text-left px-4 sm:px-5 py-3.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide whitespace-nowrap">Generated At</th>
                  <th className="text-left px-4 sm:px-5 py-3.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide whitespace-nowrap">By</th>
                  <th className="text-left px-4 sm:px-5 py-3.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide whitespace-nowrap">Size</th>
                  <th className="text-left px-4 sm:px-5 py-3.5 text-xs font-semibold text-muted-foreground uppercase tracking-wide whitespace-nowrap">Status</th>
                  <th className="px-4 sm:px-5 py-3.5 text-right text-xs font-semibold text-muted-foreground uppercase tracking-wide whitespace-nowrap">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {reports.length === 0 && (
                  <tr>
                    <td colSpan={7} className="px-5 py-8 text-center text-sm text-muted-foreground">
                      No reports generated yet this session.
                    </td>
                  </tr>
                )}
                {reports.map((report) => {
                  const cfg = statusConfig[report.status];
                  const Icon = cfg.icon;
                  const canDownload = report.status === "ready" && report.rows && report.rows.length > 0;
                  return (
                    <tr key={report.id} className="hover:bg-muted/20 transition-colors">
                      <td className="px-4 sm:px-5 py-4 text-sm font-medium text-foreground max-w-[280px] truncate">{report.name}</td>
                      <td className="px-4 sm:px-5 py-4">
                        <span className={`px-2 py-0.5 rounded-full text-xs font-medium whitespace-nowrap ${typeColors[report.type] ?? "bg-gray-100 text-gray-700"}`}>{report.type}</span>
                      </td>
                      <td className="px-4 sm:px-5 py-4 text-sm text-muted-foreground font-mono whitespace-nowrap">{report.generated_at}</td>
                      <td className="px-4 sm:px-5 py-4 text-sm text-muted-foreground whitespace-nowrap">{report.generated_by}</td>
                      <td className="px-4 sm:px-5 py-4 text-sm text-muted-foreground whitespace-nowrap">{report.size}</td>
                      <td className="px-4 sm:px-5 py-4">
                        <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium whitespace-nowrap ${cfg.className}`}>
                          <Icon className="w-3 h-3" />
                          {cfg.label}
                        </span>
                      </td>
                      <td className="px-4 sm:px-5 py-4">
                        <div className="flex items-center justify-end gap-1">
                          <button
                            type="button"
                            onClick={() => handleDownloadPdf(report)}
                            disabled={!canDownload}
                            aria-label={`Download ${report.name} as PDF`}
                            className="p-2 rounded-lg hover:bg-primary/10 text-primary disabled:opacity-30 disabled:cursor-not-allowed focus:outline-none focus:ring-2 focus:ring-primary/40"
                          >
                            <Printer className="w-4 h-4" />
                          </button>
                          <button
                            type="button"
                            onClick={() => handleDownloadCsv(report)}
                            disabled={!canDownload}
                            aria-label={`Download ${report.name} as CSV`}
                            className="p-2 rounded-lg hover:bg-emerald-500/10 text-emerald-600 disabled:opacity-30 disabled:cursor-not-allowed focus:outline-none focus:ring-2 focus:ring-emerald-500/40"
                          >
                            <Download className="w-4 h-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* 🔒 Password Prompt */}
      <PasswordPrompt
        open={showPasswordPrompt}
        title={promptTitle}
        description={promptDescription}
        onClose={() => {
          setShowPasswordPrompt(false);
          setPendingAction(null);
        }}
        onSuccess={async () => {
          if (pendingAction) await pendingAction();
        }}
      />
    </div>
  );
}